version: '3'
services:
  backend:
    build:
      context: ./i-notes-backend
    ports:
      - "3000:3000"
    networks:
      - app-network # 用于容器中的通信。多个服务有用

  frontend:
    build:
      context: ./i-notes-frontend
    ports: 
      - "8080:8080"
    depends_on:
      - backend
    
  # nginx
  nginx:
    image:nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge