
services:
  web:
    build: .
    environment:
      - NODE_ENV=development
    networks:
      - app-network # 用于容器中的通信。多个服务有用
  mongo:
    container_name: mongo
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true  
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${DB_TYPE}://${DB_USER}:${DB_PASSWORD}@mongo:${DB_PORT}/${DB_NAME}?authSource=admin
    networks:
      - app-network
    depends_on:
      - mongo

volumes:
  mongodb_data:
networks:
  app-network:
    driver: bridge 