
services:
  web:
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./yarn.lock:/app/yarn.lock
    ports:
      - "3000:3000"
      - "8080:8080"
    develop:
        watch:
          - action: sync
            path: ./
            target: /app
  mongo:
    ports:
      - "27017:27017"
  mongo-express:
    ports:
      - 8081:8081